### ISSUE TITLE
x11/konsole: crash when resizing

### ISSUE THREAD

**Issue by kwitaszczyk** [CTSRD-CHERI/cheribsd-ports#160]
Konsole crashes in icu when resizing to large dimensions. I've found this bug when using Xvnc and 4K resolution. On real hardware, I had to resize the window to dimensions larger than my screen dimensions (2048x1152 despite of a 4K screen).

Steps to reproduce on hardware:
1. Move a window to the top left corner
2. Using the bottom right corner, not the maximise button, resize the window to the maximum size
3. If Konsole hasn't crashed yet, move the window to the left, outside screen boundaries, leaving right border visible and use the right border line to resize it to the right as much as possible. This step is not needed when using Xvnc in the full screen mode with a 4K screen

Crash:
```
Core was generated by `/usr/local/bin/konsole'.
Program terminated with signal SIGPROT, CHERI protection violation.
Capability bounds fault.
#0  0x0000000040edf1e4 in countSpaces (dest=0x4bffffc0 [E,0x4bfff770-0x4bfffff7] (invalid,sealed) u"︀\xfff7\xffff", size=-597868544, spacesCountl=0xfffffff7f770 [,0xfffffff753e8-0xfffffff75688] (invalid), spacesCountr=0x40521ac1 <Konsole::TerminalDisplay::bidiMap(Konsole::Character*, QString&, int*, int*, unsigned short*, int*, bool&, bool, bool) const+996> [rxR,0x402d8000-0x40650000] (sentry)) at ushape.cpp:466
466	ushape.cpp: No such file or directory.
[Current thread is 1 (LWP 100613)]
(gdb) bt
#0  0x0000000040edf1e4 in countSpaces (dest=0x4bffffc0 [E,0x4bfff770-0x4bfffff7] (invalid,sealed) u"︀\xfff7\xffff", size=-597868544, spacesCountl=0xfffffff7f770 [,0xfffffff753e8-0xfffffff75688] (invalid), spacesCountr=0x40521ac1 <Konsole::TerminalDisplay::bidiMap(Konsole::Character*, QString&, int*, int*, unsigned short*, int*, bool&, bool, bool) const+996> [rxR,0x402d8000-0x40650000] (sentry)) at ushape.cpp:466
#1  0x0000000040ede7a8 in u_shapeArabic (source=0x6184cc20 [rwRW,0x6184cc20-0x6184d000] u' ' <repeats 200 times>..., sourceLength=305, dest=0x4bffa42c [rwRW,0x4bffa42c-0x4bffac2c] u"kw543@cheribsd:~ $", ' ' <repeats 96 times>, "\xa83b䯿", destCapacity=1024, options=9, pErrorCode=0x4bffac2c [rwRW,0x4bffac2c-0x4bffac30]) at ushape.cpp:1584
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
(gdb) 
```

**Comment by kwitaszczyk** [comment]
A fix for this issue has been submitted to upstream in https://github.com/unicode-org/icu/pull/3024.
